MVCRep(2)/Models/AdminInsert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCRep_2_.Models
{
    public class AdminInsert
    {
        [Required(ErrorMessage ="Enter the name")]
        public string name { get; set; }
        [Required(ErrorMessage = "Enter the Address")]
        public string address { get; set; }
        [Required(ErrorMessage = "Enter the phone number")]
        [RegularExpression(@"^(\d{10})$",ErrorMessage ="Enter valid phone number")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Enter the valid email")]
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        [Compare("password",ErrorMessage ="Password Mismatch")]
        public string cpassword { get; set; }
        public string adminmsg { get; set; }
    }
}

MVCRep(2)/Models/Logincls.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCRep_2_.Models
{
    public class Logincls
    {
        [Required(ErrorMessage ="Enter the Name")]
        public string Uname { get; set; }
        [Required(ErrorMessage ="Enter the Password")]
        public string password { get; set; }
        public string msg { get; set; }
        public string ltype { get; set; }
    }
}

MVCRep(2)/Models/SelectAllUsers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCRep_2_.Models
{
    public class SelectAllUsers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
    }
}

MVCRep(2)/Models/UserInsert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCRep_2_.Models
{
    public class UserInsert
    {
        [Required(ErrorMessage = "Enter the name")]
        public string name { get; set; }
        [Range(18,60,ErrorMessage ="Enter the valid age")]
        public int age { get; set; }
        [Required(ErrorMessage = "Enter the Address")]
        public string address { get; set; }
        [Required(ErrorMessage = "Enter the valid email")]
        public string email { get; set; }
        public string photo { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        [Compare("password",ErrorMessage ="Password Mismatch")]
        public string cpassword { get; set; }
        public string usermsg { get; set; }
    }
}

MVCRep(2)/Controllers/AdminRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCRep_2_.Models;
using System.Web.Mvc;

namespace MVCRep_2_.Controllers
{
    public class AdminRegController : Controller
    {
        MVCMulti2Entities dbobj = new MVCMulti2Entities();
        // GET: AdminReg
        public ActionResult Insertadmin_Load()
        {
            return View();
        }
        
        public ActionResult Insertadmin_click(AdminInsert clsobj)
        {
            if (ModelState.IsValid)
            {
                var getmaxid = dbobj.sp_MaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_adminReg(regid, clsobj.name, clsobj.address, clsobj.phone, clsobj.email);
                dbobj.sp_loginsert(regid, clsobj.username, clsobj.password, "admin");
                clsobj.adminmsg = "Successfully Inserted";
                return View("Insertadmin_Load", clsobj);
            }
            return View("Insertadmin_Load",clsobj);
        }
    }
}

MVCRep(2)/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCRep_2_.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCRep(2)/Controllers/SelectAllUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCRep_2_.Controllers
{
    public class SelectAllUserController : Controller
    {
        MVCMulti2Entities dbobj = new MVCMulti2Entities();
        // GET: SelectAllUser
        public ActionResult DisplayAll_Load()
        {
            var data = dbobj.sp_SelectAllUsers().ToList();
            ViewBag.userdetails = data;
            return View();
        }
    }
}

MVCRep(2)/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCRep_2_.Models;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;

namespace MVCRep_2_.Controllers
{
    public class UserLoginController : Controller
    {
        MVCMulti2Entities dbobj = new MVCMulti2Entities();
        // GET: UserLogin
        public ActionResult Login_Load()
        {
            return View();
        }
        public ActionResult User_Home()
        {
            return View();
        }
        public ActionResult Admin_Home()
        {
            return View();
        }
        public ActionResult Login_click(Logincls objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.Uname, objcls.password, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    var uid = dbobj.sp_loginid(objcls.Uname, objcls.password).FirstOrDefault();
                    Session["uid"] = uid;

                    var loType = dbobj.sp_loginType(objcls.Uname, objcls.password).FirstOrDefault();
                    if (loType == "user")
                    {
                        return RedirectToAction("User_Home");
                    }
                    else if (loType == "admin")
                    {
                        return RedirectToAction("Admin_Home");
                    }
                }
                
            }
            else
            {
                ModelState.Clear();
                objcls.msg = "Inavlid login";
                return View("Login_Load", objcls);
            }
            return View("Login_Load",objcls);
        }
    }
}

MVCRep(2)/Controllers/UserRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCRep_2_.Models;
using System.Web.Mvc;
using System.IO;

namespace MVCRep_2_.Controllers
{
    public class UserRegController : Controller
    {
        MVCMulti2Entities dbobj = new MVCMulti2Entities();
        // GET: UserReg
        public ActionResult Insert_Load()
        {
            return View();
        }
        public ActionResult Insert_click(UserInsert clsobj,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/photos");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\photos", fname);
                    clsobj.photo = fullpath;
                }
                var getmaxid = dbobj.sp_MaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_userReg(regid, clsobj.name,clsobj.age, clsobj.address, clsobj.email,clsobj.photo);
                dbobj.sp_loginsert(regid, clsobj.username, clsobj.password, "user");
                clsobj.usermsg = "Successfully Inserted";
                return View("Insert_Load", clsobj);
            }
            return View("Insert_click",clsobj);
        }
    }
}

MVCRep(2)/Views/AdminReg/Insertadmin_Load.cshtml
@model  MVCRep_2_.Models.AdminInsert
@{
    ViewBag.Title = "Insertadmin_Load";
}

<h2>Insert Admin Details</h2>
<div>
    @using (Html.BeginForm("Insertadmin_click", "AdminReg", FormMethod.Post))
    {
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)
        </div>
        <div>
            <label>Phone:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>
        <div>
            <label>Email:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>Username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.password)
        </div>
        <div>
            <label>Confirm Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <input type="submit" value="Insert"/>
            @Html.DisplayFor(m=>m.adminmsg)
        </div>
    }
</div>

MVCRep(2)/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCRep(2)/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCRep(2)/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCRep(2)/Views/SelectAllUser/DisplayAll_Load.cshtml
@{
    ViewBag.Title = "DisplayAll_Load";
}

<h2>Display All Details Here</h2>
<div>
    @using (Html.BeginForm("DisplayAll_Load","SelectAllUser",FormMethod.Get))
            {
                <table id="t01" class="table">
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Address</th>
                        <th>Email</th>
                        <th>Photo</th>
                    </tr>
                    @foreach (var item in ViewBag.userdetails)
                {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Age</td>
                    <td>@item.Address</td>
                    <td>@item.Email</td>
                    <td>
                        <img src="@Url.Content(item.Photo)" alt="Image" height="150" width="150"/>
                    </td>
                </tr>
                }
                </table>
            }
</div>
<style>
    #t01{
        background-color:crimson;
    }
    h1{
        color:black;
    }
    #t01 th{
        color:antiquewhite;
        background-color:black;
    }
    #t01 td{
        color:blueviolet;
        padding:40px;
    }
</style>

MVCRep(2)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCRep(2)/Views/UserLogin/Admin_Home.cshtml
@{
    ViewBag.Title = "Admin_Home";
}

<h2>You're in Admin_Home</h2>

MVCRep(2)/Views/UserLogin/Login_Load.cshtml
@model MVCRep_2_.Models.Logincls
@{
    ViewBag.Title = "Login_Load";
}

<h2>User LogIn</h2>
<div>

    @using (Html.BeginForm("Login_click", "UserLogin", FormMethod.Get)) 
    { 
        <div>
        <label>User Name</label>
        </div>
         <div>
        @Html.TextBoxFor(m=>m.Uname)
        @Html.ValidationMessageFor(m=>m.Uname)
        </div>
    <div>
        <label>Password</label>
    </div>
    <div>
        @Html.PasswordFor(m=>m.password)
        @Html.ValidationMessageFor(m=>m.password)
    </div>
    <div>
        <input type="submit" value="Login"/>
        @Html.DisplayFor(m=>m.msg)
    </div>
    }
</div>

MVCRep(2)/Views/UserLogin/User_Home.cshtml
@{
    ViewBag.Title = "User_Home";
}

<h2>You're in User_Home</h2>
<div>
    @Html.ActionLink("View User Profile","Profile_Load","ProfileDB")
</div>

MVCRep(2)/Views/UserReg/Insert_Load.cshtml
@model MVCRep_2_.Models.UserInsert
@{
    ViewBag.Title = "Insert_Load";
}

<h2>User Details</h2>
<div>
    @using (Html.BeginForm("Insert_click", "UserReg", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div>
            <label>Age:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.age)
            @Html.ValidationMessageFor(m => m.age)
        </div>
        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)
        </div>
        <div>
            <label>Email:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>Photo:</label>
        </div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
        </div>
        <div>
            <label>User name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>
        <div>
            <label>password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.password)
        </div>
        <div>
            <label>Confirm Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <input type="submit" value="Insert"/>
            @Html.DisplayFor(m=>m.usermsg)
        </div>
    }
</div>